import { composeNukta } from "@/lib/utils/bangla";

interface ArabicEquivalent {
  match: readonly string[];
  arabic: readonly string[];
  wholeWord?: boolean;
  alsoRequires?: readonly string[];
}

const EQUIVALENTS: readonly ArabicEquivalent[] = [
  {
    match: ["নামাজ", "নামায", "সালাত", "সলাত", "prayer", "salat", "salah", "namaz"],
    arabic: ["الصلاة", "صلاة"],
  },
  {
    match: ["রোজা", "রোযা", "সিয়াম", "সাওম", "সওম", "fasting", "sawm", "roza"],
    arabic: ["الصيام", "الصوم", "صوم"],
  },
  { match: ["রমজান", "রমযান", "রামাদান", "রামাযান"], arabic: ["رمضان"] },
  { match: ["জাকাত", "যাকাত", "যাকাহ", "zakat", "zakah"], arabic: ["الزكاة", "زكاة"] },
  { match: ["ফিতরা", "ফিতর"], arabic: ["الفطر", "زكاة الفطر"] },
  { match: ["সদকা", "সাদাকা", "সাদাকাহ", "charity"], arabic: ["الصدقة"] },
  { match: ["হজ", "হজ্জ", "হাজ্জ", "হজ্ব", "hajj", "pilgrimage"], arabic: ["الحج", "حج"] },
  { match: ["উমরা", "উমরাহ", "ওমরা", "umrah"], arabic: ["العمرة"] },
  { match: ["ইহরাম", "এহরাম"], arabic: ["الإحرام", "المحرم"] },
  { match: ["তাওয়াফ", "তওয়াফ"], arabic: ["الطواف"] },
  { match: ["অজু", "ওজু", "ওযু", "উযু", "অযু", "wudu"], arabic: ["الوضوء", "وضوء"] },
  { match: ["তায়াম্মুম", "তাইয়াম্মুম"], arabic: ["التيمم"] },
  { match: ["গোসল", "গুসল"], arabic: ["الغسل", "غسل"] },
  { match: ["পবিত্রতা", "নাপাক", "তাহারাত"], arabic: ["الطهارة", "طهارة"] },
  { match: ["হায়েজ", "হায়েয", "ঋতুস্রাব"], arabic: ["الحيض", "الحائض"] },
  { match: ["নিফাস"], arabic: ["النفاس"] },
  { match: ["আযান", "আজান"], arabic: ["الأذان"] },
  { match: ["ইমাম", "ইমামতি", "জামাআত", "জামাত"], arabic: ["الإمام", "الجماعة"] },
  { match: ["জুমা", "জুমুআ", "জুম্মা"], arabic: ["الجمعة"] },
  { match: ["ঈদ"], arabic: ["العيد", "العيدين"] },
  { match: ["জানাযা", "জানাজা"], arabic: ["الجنازة", "الجنائز"] },
  { match: ["কাফন", "দাফন", "কবর"], arabic: ["الكفن", "الدفن", "القبر"] },
  { match: ["ইতিকাফ", "এতেকাফ"], arabic: ["الاعتكاف"] },
  { match: ["কাযা", "কাজা"], arabic: ["القضاء"] },
  { match: ["কাফফারা", "কাফ্ফারা"], arabic: ["الكفارة"] },
  { match: ["কুরবানি", "কোরবানি", "কুরবানী"], arabic: ["الأضحية", "الأضاحي"] },
  { match: ["আকিকা", "আকীকা"], arabic: ["العقيقة"] },
  { match: ["জবাই", "যবেহ", "জবেহ"], arabic: ["الذبائح", "الذكاة"] },
  { match: ["সুদ", "রিবা", "interest", "usury", "riba"], arabic: ["الربا"] },
  { match: ["মদ", "মদ্যপান", "শরাব", "খামর", "মাদক"], arabic: ["الخمر", "المسكر"] },
  { match: ["জুয়া"], arabic: ["الميسر", "القمار"] },
  { match: ["বিয়ে", "বিবাহ", "নিকাহ", "marriage"], arabic: ["النكاح", "نكاح"] },
  { match: ["মোহর", "মোহরানা", "দেনমোহর"], arabic: ["الصداق", "المهر"] },
  { match: ["তালাক", "ত্বলাক", "divorce"], arabic: ["الطلاق"] },
  { match: ["খোলা", "খুলা"], arabic: ["الخلع"] },
  { match: ["ইদ্দত"], arabic: ["العدة"] },
  { match: ["দুধ", "দুগ্ধপান", "রাদাআ"], arabic: ["الرضاع"] },
  { match: ["ভরণপোষণ", "নাফাকা"], arabic: ["النفقة", "النفقات"] },
  {
    match: ["মিরাস", "উত্তরাধিকার", "ওয়ারিশ", "inheritance"],
    arabic: ["الميراث", "المواريث", "الفرائض"],
  },
  { match: ["অসিয়ত", "ওসিয়ত", "উইল"], arabic: ["الوصية", "الوصايا"] },
  { match: ["এতিম", "ইয়াতিম", "ইয়াতীম", "orphan"], arabic: ["اليتيم", "اليتامى"] },
  { match: ["ক্রয়", "বিক্রয়", "বেচাকেনা", "ব্যবসা"], arabic: ["البيع", "البيوع"] },
  { match: ["ঋণ", "কর্জ", "দেনা"], arabic: ["الدين", "القرض"] },
  { match: ["বন্ধক"], arabic: ["الرهن"] },
  { match: ["ভাড়া", "ইজারা"], arabic: ["الإجارة"] },
  { match: ["ওয়াকফ", "ওয়াক্ফ"], arabic: ["الوقف"] },
  { match: ["সাক্ষ্য", "সাক্ষী"], arabic: ["الشهادة", "الشهادات"] },
  { match: ["বিচার", "কাজী", "বিচারক"], arabic: ["القضاء", "القاضي"] },
  { match: ["যিনা", "জিনা", "ব্যভিচার"], arabic: ["الزنا"] },
  { match: ["চুরি", "চোর"], arabic: ["السرقة", "السارق"] },
  { match: ["হত্যা", "খুন", "কিসাস"], arabic: ["القتل", "القصاص"] },
  { match: ["দিয়াত", "রক্তপণ"], arabic: ["الدية", "الديات"] },
  { match: ["শপথ", "কসম"], arabic: ["اليمين", "الأيمان"] },
  { match: ["মান্নত", "নজর"], arabic: ["النذر", "النذور"] },
  { match: ["জিহাদ", "জেহাদ"], arabic: ["الجهاد"] },
  {
    match: ["পর্দা", "হিজাব", "ওড়না", "জিলবাব", "বোরকা"],
    arabic: ["الحجاب", "العورة", "الخمار", "الجلباب"],
  },
  { match: ["ঈমান", "ইমান"], arabic: ["الإيمان"] },
  { match: ["তাওহীদ", "তাওহিদ"], arabic: ["التوحيد"] },
  { match: ["শিরক", "শির্ক"], arabic: ["الشرك"] },
  { match: ["কুরআন", "কোরআন", "কোরান"], arabic: ["القرآن"] },
  { match: ["সুন্নত", "সুন্নাত", "সুন্নাহ"], arabic: ["السنة"] },
  { match: ["কিবলা", "কিবলাহ", "কেবলা"], arabic: ["القبلة"] },
  { match: ["মসজিদ"], arabic: ["المسجد"] },
  { match: ["খিলাফত", "খলিফা", "ইমামত"], arabic: ["الإمامة", "الخلافة"] },
  { match: ["কিয়াস", "কেয়াস", "qiyas", "kiyas", "analogy", "analogical"], arabic: ["القياس"] },
  { match: ["ইল্লত", "ইল্লাত", "illah", "ratio legis"], arabic: ["العلة"] },
  { match: ["ইসতিহসান", "ইস্তিহসান", "istihsan"], arabic: ["الاستحسان"] },
  { match: ["ইজতিহাদ", "ইজতেহাদ", "ijtihad"], arabic: ["الاجتهاد"] },
  { match: ["তাকলিদ", "তাকলীদ", "taqlid"], arabic: ["التقليد"] },
  { match: ["ইসতিসহাব", "ইস্তিসহাব", "istishab"], arabic: ["الاستصحاب"] },
  { match: ["মাসলাহা", "মাসালিহ", "maslaha"], arabic: ["المصلحة", "المصالح المرسلة"] },
  { match: ["সাদৃশ্য", "শাবাহ"], arabic: ["الشبه"] },
  { match: ["হিজরত", "হিজরাত", "hijrah", "hijra"], arabic: ["الهجرة"] },
  { match: ["বদর", "badr"], arabic: ["بدر"] },
  { match: ["উহুদ", "ওহুদ", "uhud"], arabic: ["غزوة أحد"] },
  { match: ["খন্দক", "আহযাব", "khandaq"], arabic: ["الخندق", "الأحزاب"] },
  { match: ["হুদায়বিয়া", "হুদাইবিয়া", "hudaybiyyah"], arabic: ["الحديبية"] },
  { match: ["খায়বার", "খাইবার", "khaybar"], arabic: ["خيبر"] },
  { match: ["মক্কা বিজয়", "মক্কা বিজয়"], arabic: ["فتح مكة"] },
  { match: ["হুনাইন", "হুনায়ন"], arabic: ["حنين"] },
  { match: ["তাবুক"], arabic: ["تبوك"] },
  { match: ["মুতা", "মূতা"], arabic: ["مؤتة"] },
  { match: ["মিরাজ", "মেরাজ", "ইসরা"], arabic: ["الإسراء", "المعراج"] },
  { match: ["ওহী", "অহী", "ওহি"], arabic: ["الوحي"] },
  { match: ["নবুওয়াত", "নবুয়ত"], arabic: ["النبوة", "المبعث"] },
  { match: ["বিদায় হজ", "বিদায় হজ্জ"], arabic: ["حجة الوداع"] },
  { match: ["আকাবা"], arabic: ["العقبة"] },
  { match: ["খাদিজা", "খাদীজা"], arabic: ["خديجة"] },
  { match: ["আবু তালিব"], arabic: ["أبي طالب", "أبو طالب"] },
  { match: ["শামাইল", "শামায়েল", "দৈহিক গঠন"], arabic: ["الشمائل", "صفة"] },
  { match: ["গাযওয়া", "গাজওয়া", "সারিয়্যা"], arabic: ["غزوة", "سرية"] },
  {
    match: ["সাহাবী", "সাহাবা", "সাহাবি", "companions", "sahabah"],
    arabic: ["الصحابة", "الصحابي"],
  },
  {
    match: ["উম্মাহাতুল মুমিনীন", "উম্মুল মুমিনীন", "আম্মাজান", "নবীপত্নী", "নবীজির স্ত্রী"],
    arabic: ["أمهات المؤمنين", "أزواج النبي"],
  },
  { match: ["তাবেয়ী", "তাবেঈ", "তাবিয়ী", "tabi'in"], arabic: ["التابعين"] },
  { match: ["আদম", "adam"], arabic: ["آدم عليه السلام", "خلق آدم"], wholeWord: true },
  { match: ["নূহ", "নুহ", "noah", "nuh"], arabic: ["نوح"], wholeWord: true },
  { match: ["ইদরীস", "ইদরিস"], arabic: ["إدريس عليه السلام"], wholeWord: true },
  { match: ["হূদ", "হুদ"], arabic: ["هود عليه السلام", "عاد"], wholeWord: true },
  { match: ["সালেহ", "সালিহ"], arabic: ["صالح عليه السلام", "ثمود", "الناقة"], wholeWord: true },
  {
    match: ["ইবরাহীম", "ইব্রাহিম", "ইবরাহিম", "ইব্রাহীম", "abraham", "ibrahim"],
    arabic: ["إبراهيم الخليل", "إبراهيم عليه السلام", "الخليل"],
    wholeWord: true,
  },
  { match: ["লূত", "লুত"], arabic: ["لوط"], wholeWord: true },
  {
    match: ["ইসমাঈল", "ইসমাইল", "ismail"],
    arabic: ["إسماعيل عليه السلام", "الذبيح"],
    wholeWord: true,
  },
  { match: ["ইসহাক"], arabic: ["إسحاق عليه السلام"], wholeWord: true },
  {
    match: ["ইয়াকুব", "ইয়াকূব", "yaqub"],
    arabic: ["يعقوب عليه السلام", "إسرائيل"],
    wholeWord: true,
  },
  {
    match: ["ইউসুফ", "ইউসূফ", "joseph", "yusuf"],
    arabic: ["يوسف عليه السلام", "قصة يوسف"],
    wholeWord: true,
  },
  { match: ["আইয়ুব", "আইয়ূব", "আইউব", "ayyub"], arabic: ["أيوب عليه السلام"], wholeWord: true },
  { match: ["শুআইব", "শোয়াইব", "শুয়াইব"], arabic: ["شعيب عليه السلام", "مدين"], wholeWord: true },
  {
    match: ["মূসা", "মুসা", "moses", "musa"],
    arabic: ["موسى عليه السلام", "فرعون"],
    wholeWord: true,
  },
  { match: ["হারুন", "হারূন"], arabic: ["هارون عليه السلام"], wholeWord: true },
  { match: ["দাউদ", "দাঊদ", "david", "dawud"], arabic: ["داود عليه السلام"], wholeWord: true },
  {
    match: ["সুলাইমান", "সোলায়মান", "সুলায়মান", "solomon"],
    arabic: ["سليمان بن داود", "سليمان عليه السلام"],
    wholeWord: true,
  },
  {
    match: ["ইউনুস", "ইউনূস", "jonah", "yunus"],
    arabic: ["يونس بن متى", "يونس عليه السلام", "ذا النون"],
    wholeWord: true,
  },
  { match: ["যাকারিয়া", "জাকারিয়া", "zakariya"], arabic: ["زكريا عليه السلام"], wholeWord: true },
  {
    match: ["ইয়াহইয়া", "ইয়াহিয়া", "yahya"],
    arabic: ["يحيى بن زكريا", "يحيى عليه السلام"],
    wholeWord: true,
  },
  {
    match: ["ঈসা", "ইসা", "jesus", "isa"],
    arabic: ["عيسى ابن مريم", "عيسى عليه السلام", "المسيح"],
    wholeWord: true,
  },
  {
    match: ["মারইয়াম", "মরিয়ম", "মারিয়াম", "mary", "maryam"],
    arabic: ["مريم"],
    wholeWord: true,
  },
  {
    match: ["আবু বকর", "আবু বাকর", "abu bakr"],
    arabic: ["أبو بكر الصديق", "أبي بكر الصديق", "أبا بكر الصديق"],
    wholeWord: true,
  },
  { match: ["উমর", "ওমর", "umar"], arabic: ["عمر بن الخطاب", "الفاروق"], wholeWord: true },
  { match: ["উসমান", "ওসমান", "uthman"], arabic: ["عثمان بن عفان", "ذو النورين"], wholeWord: true },
  { match: ["আলী", "আলি", "ali"], arabic: ["علي بن أبي طالب"], wholeWord: true },
  {
    match: ["মুআবিয়া", "মুয়াবিয়া", "muawiya"],
    arabic: ["معاوية بن أبي سفيان"],
    wholeWord: true,
  },
  { match: ["আয়েশা", "আয়িশা", "আয়শা", "aisha"], arabic: ["عائشة"], wholeWord: true },
  { match: ["হাফসা"], arabic: ["حفصة"], wholeWord: true },
  { match: ["সাওদা", "সওদা"], arabic: ["سودة"], wholeWord: true },
  { match: ["উম্মে সালামা", "উম্মু সালামা"], arabic: ["أم سلمة"], wholeWord: true },
  {
    match: ["যয়নব", "যাইনাব", "জয়নব"],
    arabic: ["زينب بنت جحش", "زينب بنت خزيمة", "زينب بنت رسول الله"],
    wholeWord: true,
  },
  { match: ["জুওয়াইরিয়া", "জুয়াইরিয়া"], arabic: ["جويرية"], wholeWord: true },
  {
    match: ["সাফিয়্যা", "সাফিয়া"],
    arabic: ["صفية بنت حيي", "صفية بنت عبد المطلب"],
    wholeWord: true,
  },
  { match: ["মাইমুনা", "মায়মুনা"], arabic: ["ميمونة"], wholeWord: true },
  { match: ["উম্মে হাবিবা", "উম্মু হাবিবা"], arabic: ["أم حبيبة"], wholeWord: true },
  {
    match: ["ফাতিমা", "ফাতেমা", "fatima"],
    arabic: ["فاطمة بنت رسول الله", "فاطمة الزهراء", "فاطمة بنت محمد"],
    wholeWord: true,
  },
  { match: ["আসিয়া", "আছিয়া"], arabic: ["آسية"], wholeWord: true },
  { match: ["সুমাইয়া", "সুমাইয়্যা"], arabic: ["سمية"], wholeWord: true },
  {
    match: ["রাবেয়া বসরী", "রাবেয়া বসরি", "রাবিয়া"],
    arabic: ["رابعة العدوية"],
    wholeWord: true,
  },
  { match: ["হামযা", "হামজা"], arabic: ["حمزة بن عبد المطلب", "سيد الشهداء"], wholeWord: true },
  { match: ["বিলাল", "বেলাল"], arabic: ["بلال بن رباح", "بلال"], wholeWord: true },
  { match: ["আবু হুরায়রা", "আবু হুরাইরা"], arabic: ["هريرة"], wholeWord: true },
  { match: ["খালিদ", "খালেদ"], arabic: ["خالد بن الوليد"], wholeWord: true },
  { match: ["সালমান ফারসি", "সালমান ফারসী"], arabic: ["سلمان الفارسي"], wholeWord: true },
  {
    match: ["ইবনে আব্বাস", "ইবনু আব্বাস", "ইবন আব্বাস"],
    arabic: ["ابن عباس", "عبد الله بن عباس"],
    wholeWord: true,
  },
  {
    match: ["ইবনে মাসউদ", "ইবনু মাসউদ"],
    arabic: ["ابن مسعود", "عبد الله بن مسعود"],
    wholeWord: true,
  },
  {
    match: ["আবু হানিফা", "আবু হানীফা", "হানাফী", "হানাফি", "abu hanifa", "hanafi"],
    arabic: ["أبو حنيفة", "أبي حنيفة", "الحنفية"],
    wholeWord: true,
  },
  {
    match: ["ইমাম মালিক", "ইমাম মালেক", "মালিকী", "মালেকী", "maliki"],
    arabic: ["مالك بن أنس", "الإمام مالك", "المالكية"],
    wholeWord: true,
  },
  {
    match: ["শাফেয়ী", "শাফিঈ", "শাফেঈ", "শাফেয়ি", "shafi'i", "shafii"],
    arabic: ["الشافعي", "الشافعية"],
    wholeWord: true,
  },
  {
    match: ["আহমদ ইবনে হাম্বল", "আহমাদ ইবনু হাম্বল", "হাম্বলী", "হাম্বলি", "hanbali"],
    arabic: ["أحمد بن حنبل", "الحنابلة"],
    wholeWord: true,
  },
  { match: ["ইমাম বুখারী", "ইমাম বুখারি"], arabic: ["البخاري"], wholeWord: true },
  { match: ["হাসান বসরী", "হাসান বাসরী"], arabic: ["الحسن البصري"], wholeWord: true },
  {
    match: ["ইস্তেহাযা", "ইস্তিহাযা", "ইস্তিহাজা", "ইস্তেহাজা", "istihadha", "irregular bleeding"],
    arabic: ["الاستحاضة", "المستحاضة"],
  },
  {
    match: ["menstruation", "menstruating", "menses", "hayez", "haiz"],
    arabic: ["الحيض", "الحائض"],
  },
  {
    match: ["মুসাফির", "মুসাফির", "সফর", "traveller", "traveler", "travelling", "musafir"],
    arabic: ["المسافر", "السفر"],
  },
  {
    match: ["কসর", "কছর", "qasr"],
    arabic: ["قصر الصلاة", "القصر", "صلاة المسافر", "نوى الإقامة", "مسيرة ثلاثة أيام"],
    wholeWord: true,
  },
  {
    match: ["shorten", "shortening"],
    alsoRequires: ["prayer", "salah", "travel", "traveller", "traveler", "journey"],
    arabic: ["قصر الصلاة", "صلاة المسافر", "نوى الإقامة", "مسيرة ثلاثة أيام"],
  },
  { match: ["মুক্তাদি", "মুকতাদি", "muqtadi"], arabic: ["المأموم", "المقتدي"] },
  { match: ["কেরাত", "কিরাত", "কিরাআত", "ক্বিরাত", "qirat", "recit"], arabic: ["القراءة"] },
  { match: ["তিলাওয়াত", "তেলাওয়াত", "tilawat"], arabic: ["القراءة", "تلاوة القرآن"] },
  { match: ["জোরে", "উচ্চস্বরে", "aloud", "loudly"], arabic: ["الجهر"], wholeWord: true },
  { match: ["আস্তে", "নিঃশব্দে", "quietly", "silently"], arabic: ["الإسرار"], wholeWord: true },
  { match: ["কণ্ঠস্বর", "আওয়াজ", "voice"], arabic: ["صوت المرأة", "الصوت"] },
  {
    match: ["মাসিক", "পিরিয়ড", "period", "masik"],
    alsoRequires: [
      "নামাজ",
      "নামায",
      "রোজা",
      "রক্ত",
      "অনিয়মিত",
      "স্রাব",
      "namaz",
      "prayer",
      "salah",
      "roza",
      "irregular",
      "oniyomito",
      "bleeding",
    ],
    arabic: ["الحيض", "الاستحاضة", "المستحاضة"],
  },
  {
    match: ["মহিলা", "নারী", "মেয়ে", "women", "woman", "female", "mohila", "nari", "meye"],
    alsoRequires: [
      "জোরে",
      "উচ্চস্বরে",
      "কণ্ঠ",
      "আওয়াজ",
      "গলা",
      "স্বর",
      "loud",
      "aloud",
      "voice",
      "jore",
      "awaj",
      "kontho",
    ],
    arabic: ["نغمة المرأة", "صوت المرأة", "المرأة لا ترفع صوتها"],
  },
  {
    match: ["ব্যান্ডেজ", "প্লাস্টার", "জাবিরা", "bandage", "splint"],
    arabic: ["الجبيرة", "الجبائر"],
  },
  { match: ["মাসেহ", "মাসাহ", "মাসহ", "masah", "wiping"], arabic: ["المسح"] },
  { match: ["মোজা", "socks", "khuff"], arabic: ["المسح على الخفين", "الخفين"], wholeWord: true },
  { match: ["নিসাব", "নেসাব", "nisab"], arabic: ["النصاب"] },
  { match: ["অগ্রিম যাকাত", "অগ্রিম জাকাত", "advance zakat"], arabic: ["تعجيل الزكاة"] },
  { match: ["উকিল", "ওকালত", "প্রতিনিধি", "agent", "wakil"], arabic: ["الوكالة", "الوكيل"] },
  { match: ["অভিভাবক", "ওলি", "wali", "guardian"], arabic: ["الولي", "الولاية"], wholeWord: true },
  { match: ["লোন", "loan", "mortgage"], arabic: ["القرض", "الربا"] },
  { match: ["আত্মহত্যা", "suicide"], arabic: ["قتل نفسه", "قاتل نفسه", "الانتحار"] },
  {
    match: ["জ্যোতিষ", "রাশিফল", "গণক", "গণনা", "astrology", "horoscope", "fortune teller"],
    arabic: ["الكهانة", "العراف", "التنجيم"],
  },
  { match: ["গাধা", "donkey"], arabic: ["الحمر الأهلية", "الحمار"] },
  { match: ["মাকরূহ", "মাকরুহ", "মাকরুহ", "makruh"], arabic: ["مكروه", "الكراهة"] },
  { match: ["বিতর", "বেতের", "witr"], arabic: ["الوتر"], wholeWord: true },
  { match: ["তারাবীহ", "তারাবিহ", "তারাবি", "tarawih"], arabic: ["التراويح", "قيام رمضان"] },
  { match: ["সাহু", "sahw"], arabic: ["سجود السهو"], wholeWord: true },
  { match: ["দাড়ি", "beard"], arabic: ["اللحية"], wholeWord: true },
  {
    match: ["গান", "বাদ্যযন্ত্র", "music", "singing"],
    arabic: ["الغناء", "المعازف"],
    wholeWord: true,
  },
  { match: ["ছবি", "ফটো", "photograph", "picture"], arabic: ["التصوير", "الصور"] },
  { match: ["মাযহাব", "মাজহাব", "madhhab"], arabic: ["مذهب", "المذهب"] },
  { match: ["ফতোয়া", "ফতওয়া", "fatwa"], arabic: ["الفتوى", "فتوى"] },
];

const BOUNDARY = String.raw`(?:^|[\s,.।?!"'()\[\]/:;-])`;
const WORD_END = String.raw`(?:ের|এর|য়ের|র|কে|ও)?(?=$|[\s,.।?!"'()\[\]/:;-])`;

function termPattern(terms: readonly string[], wholeWord: boolean | undefined): RegExp {
  return new RegExp(
    `${BOUNDARY}(?:${terms.map((term) => composeNukta(term).replace(/[.*+?^${}()|[\]\\]/g, "\\$&")).join("|")})${wholeWord ? WORD_END : ""}`,
    "iu",
  );
}

const MATCHERS = EQUIVALENTS.map((entry) => ({
  arabic: entry.arabic,
  required: entry.alsoRequires ? termPattern(entry.alsoRequires, false) : null,
  pattern: new RegExp(
    `${BOUNDARY}(?:${entry.match.map((term) => composeNukta(term).replace(/[.*+?^${}()|[\]\\]/g, "\\$&")).join("|")})${entry.wholeWord ? WORD_END : ""}`,
    "iu",
  ),
}));

export function arabicQueryTerms(query: string): string[] {
  const normalized = composeNukta(query);
  return [
    ...new Set(
      MATCHERS.filter(
        ({ pattern, required }) =>
          pattern.test(normalized) && (required === null || required.test(normalized)),
      ).flatMap(({ arabic }) => arabic),
    ),
  ];
}
